const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
        new BabyChicken(),
    ],
    [
        new Endboss(),
    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
    ],
    [
        new BackgroundObject('assets/img/5_background/layers/air.png', -1080, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/2.png', -1080, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/2.png', -1080, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/2.png', -1080, 720),

        new BackgroundObject('assets/img/5_background/layers/air.png', 0, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/1.png', 0, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/1.png', 0, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/1.png', 0, 720),
        new BackgroundObject('assets/img/5_background/layers/air.png', 1080, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/2.png', 1080, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/2.png', 1080, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/2.png', 1080, 720),

        new BackgroundObject('assets/img/5_background/layers/air.png', 2160, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/1.png', 2160, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/1.png', 2160, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/1.png', 2160, 720),
        new BackgroundObject('assets/img/5_background/layers/air.png', 3240, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/2.png', 3240, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/2.png', 3240, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/2.png', 3240, 720),

        new BackgroundObject('assets/img/5_background/layers/air.png', 4320, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/1.png', 4320, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/1.png', 4320, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/1.png', 4320, 720),
        new BackgroundObject('assets/img/5_background/layers/air.png', 5400, 720),
        new BackgroundObject('assets/img/5_background/layers/3_third_layer/2.png', 5400, 720),
        new BackgroundObject('assets/img/5_background/layers/2_second_layer/2.png', 5400, 720),
        new BackgroundObject('assets/img/5_background/layers/1_first_layer/2.png', 5400, 720),
    ]
)